require 'packer_setup'
require 'core.options'
require 'core.colors'
require 'core.keymappings'
require 'core.autocmd'

require 'lsp-config'
require 'lsp-config.nvim-cmp'

require 'plugins.startup'
require 'plugins.whichkeys'
require 'plugins.bufferline'
require 'plugins.trouble'
require 'plugins.telescope'
require 'plugins.nvim-tree'
require 'plugins.gitsigns'
require 'plugins.comment'
require 'plugins.lualine'
require 'plugins.copilot'
require 'plugins.floatterm'
require 'plugins.coverage'
require 'plugins.vim-test'
